### ISSUE TITLE
Would it be possible to add a license like the MIT License so that other projects can expand on this?

### ISSUE THREAD

**Issue by DrewNaylor** [malcolmstill/compositor.net#1]
As it is right now without a license, nobody else can use the code, but it could be useful in other projects or be expanded further by forks. Specifically, I'd like to use it for one of my projects, but the lack of a license prevents me from changing or using the code.

**Comment by malcolmstill** [comment]
@DrewNaylor done!

**Comment by DrewNaylor** [comment]
Thank you!
